package com.degla.restful.models;

/**
 * Created by snouto on 18/05/15.
 */
public enum FileModelStates {
    CHECKED_IN, CHECKED_OUT, MISSING, RECEPTIONIST_IN, RECEPTIONIST_OUT, KEEPER_IN, COORDINATOR_IN, COORDINATOR_OUT, NEW,
    DISTRIBUTED,OUT_OF_CABIN,TRANSFERRED,PROCESSING_COORDINATOR,ANALYSIS_COORDINATOR,CODING_COORDINATOR,INCOMPLETE_COORDINATOR,INPATIENT_COMPLETED,
    TEMPORARY_STORED;
}
